# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choice_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Central_MainWindow(object):
    def setupUi(self, Central_MainWindow):
        Central_MainWindow.setObjectName("Central_MainWindow")
        Central_MainWindow.resize(730, 564)
        Central_MainWindow.setAutoFillBackground(False)
        Central_MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Central_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.type_crypt = QtWidgets.QComboBox(self.centralwidget)
        self.type_crypt.setGeometry(QtCore.QRect(90, 410, 151, 31))
        self.type_crypt.setObjectName("type_crypt")
        self.type_crypt.addItem("")
        self.type_crypt.addItem("")
        self.type_crypt.addItem("")
        self.type_crypt.addItem("")
        self.type_crypt.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 601, 171))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(470, 410, 141, 31))
        self.start_button.setObjectName("start_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 731, 541))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/Admin/Desktop/1587219727_22-p-khakkerskie-foni-77.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.type_crypt.raise_()
        self.label_2.raise_()
        self.start_button.raise_()
        Central_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Central_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 730, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        Central_MainWindow.setMenuBar(self.menubar)
        self.info = QtWidgets.QAction(Central_MainWindow)
        self.info.setObjectName("info")
        self.help = QtWidgets.QAction(Central_MainWindow)
        self.help.setObjectName("help")
        self.history = QtWidgets.QAction(Central_MainWindow)
        self.history.setObjectName("history")
        self.menu.addAction(self.info)
        self.menu.addAction(self.help)
        self.menu.addAction(self.history)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Central_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Central_MainWindow)

    def retranslateUi(self, Central_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Central_MainWindow.setWindowTitle(_translate("Central_MainWindow", "AMGINE"))
        self.type_crypt.setItemText(0, _translate("Central_MainWindow", "Шифр Вижинера"))
        self.type_crypt.setItemText(1, _translate("Central_MainWindow", "Азбука Морзе"))
        self.type_crypt.setItemText(2, _translate("Central_MainWindow", "Шифр Цезаря"))
        self.type_crypt.setItemText(3, _translate("Central_MainWindow", "Моноалфавит"))
        self.type_crypt.setItemText(4, _translate("Central_MainWindow", "Системы счисления"))
        self.label_2.setText(_translate("Central_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; color:#0000ff;\">Какой язык шифрования запустить?</span></p></body></html>"))
        self.start_button.setText(_translate("Central_MainWindow", "Запустить!"))
        self.menu.setTitle(_translate("Central_MainWindow", "Меню"))
        self.info.setText(_translate("Central_MainWindow", "Инфо"))
        self.help.setText(_translate("Central_MainWindow", "Помощь"))
        self.history.setText(_translate("Central_MainWindow", "История"))
import phonk_fone_test_rc
