from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, Ui_MainWindow):
        Ui_MainWindow.setObjectName("Ui_MainWindow")
        Ui_MainWindow.resize(453, 253)
        self.centralwidget = QtWidgets.QWidget(Ui_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 461, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.start_login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_login_btn.setGeometry(QtCore.QRect(190, 170, 101, 31))
        self.start_login_btn.setObjectName("start_login_btn")
        Ui_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 453, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        Ui_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui_MainWindow)
        self.statusbar.setObjectName("statusbar")
        Ui_MainWindow.setStatusBar(self.statusbar)
        self.info = QtWidgets.QAction(Ui_MainWindow)
        self.info.setObjectName("info")
        self.help = QtWidgets.QAction(Ui_MainWindow)
        self.help.setObjectName("help")
        self.action_3 = QtWidgets.QAction(Ui_MainWindow)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.info)
        self.menu.addAction(self.help)
        self.menu.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Ui_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Ui_MainWindow)

    def retranslateUi(self, Ui_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Ui_MainWindow.setWindowTitle('Amgine')
        self.label.setText(_translate("Ui_MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Вас приветствует программа Amgine!</span></p><p align=\"center\"><span style=\" font-size:12pt;\">Подробнее о программе можно посмотреть в меню сверху.</span></p></body></html>"))
        self.start_login_btn.setText(_translate("Ui_MainWindow", "Начать!"))
        self.menu.setTitle(_translate("Ui_MainWindow", "Меню"))
        self.info.setText(_translate("Ui_MainWindow", "Инфо"))
        self.help.setText(_translate("Ui_MainWindow", "Помощь"))
        self.action_3.setText(_translate("Ui_MainWindow", "История поиска"))
