from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mono_Alpha_Add_Dict(object):
    def setupUi(self, Mono_Alpha_Add_Dict):
        Mono_Alpha_Add_Dict.setObjectName("Mono_Alpha_Add_Dict")
        Mono_Alpha_Add_Dict.resize(537, 390)
        Mono_Alpha_Add_Dict.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(Mono_Alpha_Add_Dict)
        self.centralwidget.setObjectName("centralwidget")
        self.le_key = QtWidgets.QLineEdit(self.centralwidget)
        self.le_key.setGeometry(QtCore.QRect(60, 70, 51, 21))
        self.le_key.setObjectName("le_key")
        self.le_value = QtWidgets.QLineEdit(self.centralwidget)
        self.le_value.setGeometry(QtCore.QRect(180, 70, 51, 21))
        self.le_value.setObjectName("le_value")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 70, 31, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 70, 51, 21))
        self.label_2.setObjectName("label_2")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(250, 70, 75, 23))
        self.btn_add.setObjectName("btn_add")
        self.btn_check = QtWidgets.QPushButton(self.centralwidget)
        self.btn_check.setGeometry(QtCore.QRect(20, 140, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_check.sizePolicy().hasHeightForWidth())
        self.btn_check.setSizePolicy(sizePolicy)
        self.btn_check.setObjectName("btn_check")
        self.textb_check = QtWidgets.QTextBrowser(self.centralwidget)
        self.textb_check.setGeometry(QtCore.QRect(120, 111, 411, 191))
        self.textb_check.setObjectName("textb_check")
        self.btn_save_dict = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_dict.setGeometry(QtCore.QRect(450, 320, 81, 41))
        self.btn_save_dict.setObjectName("btn_save_dict")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 241, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rb_cap_on = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rb_cap_on.setChecked(True)
        self.rb_cap_on.setObjectName("rb_cap_on")
        self.buttonGroup = QtWidgets.QButtonGroup(Mono_Alpha_Add_Dict)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rb_cap_on)
        self.horizontalLayout.addWidget(self.rb_cap_on)
        self.rb_cap_off = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_cap_off.sizePolicy().hasHeightForWidth())
        self.rb_cap_off.setSizePolicy(sizePolicy)
        self.rb_cap_off.setChecked(False)
        self.rb_cap_off.setObjectName("rb_cap_off")
        self.buttonGroup.addButton(self.rb_cap_off)
        self.horizontalLayout.addWidget(self.rb_cap_off)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(300, 0, 231, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rb_mirrior_on = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rb_mirrior_on.setChecked(True)
        self.rb_mirrior_on.setObjectName("rb_mirrior_on")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Mono_Alpha_Add_Dict)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.rb_mirrior_on)
        self.horizontalLayout_2.addWidget(self.rb_mirrior_on)
        self.rb_mirror_off = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_mirror_off.sizePolicy().hasHeightForWidth())
        self.rb_mirror_off.setSizePolicy(sizePolicy)
        self.rb_mirror_off.setObjectName("rb_mirror_off")
        self.buttonGroup_2.addButton(self.rb_mirror_off)
        self.horizontalLayout_2.addWidget(self.rb_mirror_off)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        Mono_Alpha_Add_Dict.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Mono_Alpha_Add_Dict)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 537, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        Mono_Alpha_Add_Dict.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(Mono_Alpha_Add_Dict)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(Mono_Alpha_Add_Dict)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(Mono_Alpha_Add_Dict)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Mono_Alpha_Add_Dict)
        QtCore.QMetaObject.connectSlotsByName(Mono_Alpha_Add_Dict)

    def retranslateUi(self, Mono_Alpha_Add_Dict):
        _translate = QtCore.QCoreApplication.translate
        Mono_Alpha_Add_Dict.setWindowTitle(_translate("Mono_Alpha_Add_Dict", "Angine"))
        self.label.setText(_translate("Mono_Alpha_Add_Dict", "Ключ"))
        self.label_2.setText(_translate("Mono_Alpha_Add_Dict", "Значение"))
        self.btn_add.setText(_translate("Mono_Alpha_Add_Dict", "Добавить!"))
        self.btn_check.setText(_translate("Mono_Alpha_Add_Dict", "Проверить!"))
        self.btn_save_dict.setText(_translate("Mono_Alpha_Add_Dict", "Сохранить"))
        self.label_3.setText(_translate("Mono_Alpha_Add_Dict", "<html><head/><body><p align=\"center\">Автоматическое добавление заглавных букв</p></body></html>"))
        self.rb_cap_on.setText(_translate("Mono_Alpha_Add_Dict", "Да"))
        self.rb_cap_off.setText(_translate("Mono_Alpha_Add_Dict", "Нет"))
        self.label_4.setText(_translate("Mono_Alpha_Add_Dict", "<html><head/><body><p align=\"center\">&quot;Зеркальное&quot;  добавление</p></body></html>"))
        self.rb_mirrior_on.setText(_translate("Mono_Alpha_Add_Dict", "Да"))
        self.rb_mirror_off.setText(_translate("Mono_Alpha_Add_Dict", "Нет"))
        self.label_5.setText(_translate("Mono_Alpha_Add_Dict", "Проверить алфавит"))
        self.menu.setTitle(_translate("Mono_Alpha_Add_Dict", "Меню"))
        self.action.setText(_translate("Mono_Alpha_Add_Dict", "О программе"))
        self.action_2.setText(_translate("Mono_Alpha_Add_Dict", "История"))
        self.action_3.setText(_translate("Mono_Alpha_Add_Dict", "Помощь"))
