from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mono_Alpha_Use_Dict(object):
    def setupUi(self, Mono_Alpha_Use_Dict):
        Mono_Alpha_Use_Dict.setObjectName("Mono_Alpha_Use_Dict")
        Mono_Alpha_Use_Dict.setEnabled(True)
        Mono_Alpha_Use_Dict.resize(659, 470)
        self.centralwidget = QtWidgets.QWidget(Mono_Alpha_Use_Dict)
        self.centralwidget.setObjectName("centralwidget")
        self.input_tB = QtWidgets.QTextBrowser(self.centralwidget)
        self.input_tB.setGeometry(QtCore.QRect(10, 60, 251, 191))
        self.input_tB.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextSelectableByMouse)
        self.input_tB.setObjectName("input_tB")
        self.btn_code = QtWidgets.QPushButton(self.centralwidget)
        self.btn_code.setGeometry(QtCore.QRect(290, 140, 75, 41))
        self.btn_code.setObjectName("btn_code")
        self.out_tB = QtWidgets.QTextBrowser(self.centralwidget)
        self.out_tB.setGeometry(QtCore.QRect(390, 60, 256, 192))
        self.out_tB.setObjectName("out_tB")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 251, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 20, 241, 31))
        self.label_2.setObjectName("label_2")
        self.btn_load = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load.setGeometry(QtCore.QRect(10, 310, 75, 23))
        self.btn_load.setObjectName("btn_load")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 270, 231, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 270, 161, 31))
        self.label_4.setObjectName("label_4")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(390, 310, 75, 23))
        self.btn_save.setObjectName("btn_save")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 370, 111, 21))
        self.label_5.setObjectName("label_5")
        self.btn_load_dict = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load_dict.setGeometry(QtCore.QRect(130, 370, 121, 23))
        self.btn_load_dict.setObjectName("btn_load_dict")
        self.success_load_dict = QtWidgets.QLabel(self.centralwidget)
        self.success_load_dict.setEnabled(True)
        self.success_load_dict.setGeometry(QtCore.QRect(290, 370, 221, 21))
        self.success_load_dict.setObjectName("success_load_dict")
        Mono_Alpha_Use_Dict.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Mono_Alpha_Use_Dict)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 659, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        Mono_Alpha_Use_Dict.setMenuBar(self.menubar)
        self.info = QtWidgets.QAction(Mono_Alpha_Use_Dict)
        self.info.setObjectName("info")
        self.help = QtWidgets.QAction(Mono_Alpha_Use_Dict)
        self.help.setObjectName("help")
        self.history = QtWidgets.QAction(Mono_Alpha_Use_Dict)
        self.history.setObjectName("history")
        self.menu.addAction(self.info)
        self.menu.addAction(self.help)
        self.menu.addAction(self.history)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Mono_Alpha_Use_Dict)
        QtCore.QMetaObject.connectSlotsByName(Mono_Alpha_Use_Dict)

    def retranslateUi(self, Mono_Alpha_Use_Dict):
        _translate = QtCore.QCoreApplication.translate
        Mono_Alpha_Use_Dict.setWindowTitle(_translate("Mono_Alpha_Use_Dict", "Amgine Caesar"))
        self.btn_code.setText(_translate("Mono_Alpha_Use_Dict", "→"))
        self.label.setText(_translate("Mono_Alpha_Use_Dict", "<html><head/><body><p><span style=\" font-size:12pt;\">Ввод</span></p></body></html>"))
        self.label_2.setText(_translate("Mono_Alpha_Use_Dict", "<html><head/><body><p><span style=\" font-size:12pt;\">Вывод</span></p></body></html>"))
        self.btn_load.setText(_translate("Mono_Alpha_Use_Dict", "Загрузить!"))
        self.label_3.setText(_translate("Mono_Alpha_Use_Dict", "<html><head/><body><p><span style=\" font-size:10pt;\">Загрузить текст</span></p></body></html>"))
        self.label_4.setText(_translate("Mono_Alpha_Use_Dict", "<html><head/><body><p><span style=\" font-size:10pt;\">Сохранить текст</span></p></body></html>"))
        self.btn_save.setText(_translate("Mono_Alpha_Use_Dict", "Сохранить!"))
        self.label_5.setText(_translate("Mono_Alpha_Use_Dict", "<html><head/><body><p><span style=\" font-size:10pt;\">Загрузить словарь</span></p></body></html>"))
        self.btn_load_dict.setText(_translate("Mono_Alpha_Use_Dict", "Загрузить!"))
        self.success_load_dict.setText(_translate("Mono_Alpha_Use_Dict", "<html><head/><body><p><span style=\" font-size:10pt; color:#169100;\">Словарь загружен успешно!</span></p></body></html>"))
        self.menu.setTitle(_translate("Mono_Alpha_Use_Dict", "Меню"))
        self.info.setText(_translate("Mono_Alpha_Use_Dict", "Инфо"))
        self.help.setText(_translate("Mono_Alpha_Use_Dict", "Помощь"))
        self.history.setText(_translate("Mono_Alpha_Use_Dict", "История поиска"))
