from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mono_Alpha_Use_Dict(object):
    def setupUi(self, Mono_Alpha_Use_Dict):
        Mono_Alpha_Use_Dict.setObjectName("Mono_Alpha_Use_Dict")
        Mono_Alpha_Use_Dict.setEnabled(True)
        Mono_Alpha_Use_Dict.resize(653, 423)
        self.centralwidget = QtWidgets.QWidget(Mono_Alpha_Use_Dict)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_code = QtWidgets.QPushButton(self.centralwidget)
        self.btn_code.setGeometry(QtCore.QRect(270, 110, 111, 41))
        self.btn_code.setObjectName("btn_code")
        self.textBrowser_output = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_output.setGeometry(QtCore.QRect(390, 30, 256, 211))
        self.textBrowser_output.setObjectName("textBrowser_output")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 251, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 0, 241, 31))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 320, 111, 21))
        self.label_5.setObjectName("label_5")
        self.btn_load_dict = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load_dict.setGeometry(QtCore.QRect(130, 310, 121, 41))
        self.btn_load_dict.setObjectName("btn_load_dict")
        self.success_load_dict = QtWidgets.QLabel(self.centralwidget)
        self.success_load_dict.setEnabled(True)
        self.success_load_dict.setGeometry(QtCore.QRect(270, 320, 221, 21))
        self.success_load_dict.setObjectName("success_load_dict")
        self.textBrowser_input = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_input.setGeometry(QtCore.QRect(10, 30, 251, 211))
        self.textBrowser_input.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textBrowser_input.setObjectName("textBrowser_input")
        self.btn_load_text = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load_text.setGeometry(QtCore.QRect(120, 250, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_load_text.sizePolicy().hasHeightForWidth())
        self.btn_load_text.setSizePolicy(sizePolicy)
        self.btn_load_text.setObjectName("btn_load_text")
        self.btn_save_text = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_text.setGeometry(QtCore.QRect(500, 250, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save_text.sizePolicy().hasHeightForWidth())
        self.btn_save_text.setSizePolicy(sizePolicy)
        self.btn_save_text.setObjectName("btn_save_text")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 250, 161, 31))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 250, 101, 31))
        self.label_3.setObjectName("label_3")
        self.label_error = QtWidgets.QLabel(self.centralwidget)
        self.label_error.setGeometry(QtCore.QRect(10, 360, 631, 31))
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        Mono_Alpha_Use_Dict.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Mono_Alpha_Use_Dict)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 653, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        Mono_Alpha_Use_Dict.setMenuBar(self.menubar)
        self.info = QtWidgets.QAction(Mono_Alpha_Use_Dict)
        self.info.setObjectName("info")
        self.help = QtWidgets.QAction(Mono_Alpha_Use_Dict)
        self.help.setObjectName("help")
        self.history = QtWidgets.QAction(Mono_Alpha_Use_Dict)
        self.history.setObjectName("history")
        self.menu.addAction(self.info)
        self.menu.addAction(self.help)
        self.menu.addAction(self.history)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Mono_Alpha_Use_Dict)
        QtCore.QMetaObject.connectSlotsByName(Mono_Alpha_Use_Dict)

    def retranslateUi(self, Mono_Alpha_Use_Dict):
        _translate = QtCore.QCoreApplication.translate
        Mono_Alpha_Use_Dict.setWindowTitle(_translate("Mono_Alpha_Use_Dict", "Amgine Caesar"))
        self.btn_code.setText(_translate("Mono_Alpha_Use_Dict", "→"))
        self.label.setText(_translate("Mono_Alpha_Use_Dict", "<html><head/><body><p><span style=\" font-size:12pt;\">Ввод</span></p></body></html>"))
        self.label_2.setText(_translate("Mono_Alpha_Use_Dict", "<html><head/><body><p><span style=\" font-size:12pt;\">Вывод</span></p></body></html>"))
        self.label_5.setText(_translate("Mono_Alpha_Use_Dict", "<html><head/><body><p><span style=\" font-size:10pt;\">Загрузить словарь</span></p></body></html>"))
        self.btn_load_dict.setText(_translate("Mono_Alpha_Use_Dict", "Загрузить!"))
        self.success_load_dict.setText(_translate("Mono_Alpha_Use_Dict", "<html><head/><body><p><span style=\" font-size:10pt; color:#169100;\">Словарь загружен успешно!</span></p></body></html>"))
        self.btn_load_text.setText(_translate("Mono_Alpha_Use_Dict", "Загрузка"))
        self.btn_save_text.setText(_translate("Mono_Alpha_Use_Dict", "Сохранение"))
        self.label_4.setText(_translate("Mono_Alpha_Use_Dict", "<html><head/><body><p><span style=\" font-size:10pt;\">Сохранить текст</span></p></body></html>"))
        self.label_3.setText(_translate("Mono_Alpha_Use_Dict", "<html><head/><body><p><span style=\" font-size:10pt;\">Загрузить текст</span></p></body></html>"))
        self.menu.setTitle(_translate("Mono_Alpha_Use_Dict", "Меню"))
        self.info.setText(_translate("Mono_Alpha_Use_Dict", "Инфо"))
        self.help.setText(_translate("Mono_Alpha_Use_Dict", "Помощь"))
        self.history.setText(_translate("Mono_Alpha_Use_Dict", "История поиска"))
