from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Morse_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(661, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.code_btn = QtWidgets.QPushButton(self.centralwidget)
        self.code_btn.setGeometry(QtCore.QRect(290, 140, 75, 23))
        self.code_btn.setObjectName("code_btn")
        self.textwid_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textwid_2.setGeometry(QtCore.QRect(390, 60, 261, 192))
        self.textwid_2.setObjectName("textwid_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 251, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 20, 241, 31))
        self.label_2.setObjectName("label_2")
        self.load_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_btn.setGeometry(QtCore.QRect(20, 310, 75, 23))
        self.load_btn.setObjectName("load_btn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 270, 231, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 270, 161, 31))
        self.label_4.setObjectName("label_4")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(400, 310, 75, 23))
        self.save_btn.setObjectName("save_btn")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 380, 621, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.rb_lang_eng = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.rb_lang_eng.setObjectName("rb_lang_eng")
        self.btn_group_lang = QtWidgets.QButtonGroup(MainWindow)
        self.btn_group_lang.setObjectName("btn_group_lang")
        self.btn_group_lang.addButton(self.rb_lang_eng)
        self.gridLayout.addWidget(self.rb_lang_eng, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.rb_lang_ru = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.rb_lang_ru.setObjectName("rb_lang_ru")
        self.btn_group_lang.addButton(self.rb_lang_ru)
        self.gridLayout.addWidget(self.rb_lang_ru, 0, 1, 1, 1)
        self.rb_crypt_decode = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.rb_crypt_decode.setObjectName("rb_crypt_decode")
        self.btn_group_crypt = QtWidgets.QButtonGroup(MainWindow)
        self.btn_group_crypt.setObjectName("btn_group_crypt")
        self.btn_group_crypt.addButton(self.rb_crypt_decode)
        self.gridLayout.addWidget(self.rb_crypt_decode, 1, 1, 1, 1)
        self.rb_crypt_code = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.rb_crypt_code.setObjectName("rb_crypt_code")
        self.btn_group_crypt.addButton(self.rb_crypt_code)
        self.gridLayout.addWidget(self.rb_crypt_code, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(270, 339, 121, 31))
        self.label_8.setObjectName("label_8")
        self.textwid_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.textwid_1.setGeometry(QtCore.QRect(10, 60, 251, 191))
        self.textwid_1.setObjectName("textwid_1")
        self.save_settings_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_settings_btn.setGeometry(QtCore.QRect(504, 342, 141, 31))
        self.save_settings_btn.setObjectName("save_settings_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 661, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.info = QtWidgets.QAction(MainWindow)
        self.info.setObjectName("info")
        self.help = QtWidgets.QAction(MainWindow)
        self.help.setObjectName("help")
        self.history = QtWidgets.QAction(MainWindow)
        self.history.setObjectName("history")
        self.menu.addAction(self.info)
        self.menu.addAction(self.help)
        self.menu.addAction(self.history)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Amgine Morse"))
        self.code_btn.setText(_translate("MainWindow", "→"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Ввод</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Вывод</span></p></body></html>"))
        self.load_btn.setText(_translate("MainWindow", "Загрузка"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Загрузить текст</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Сохранить текст</span></p></body></html>"))
        self.save_btn.setText(_translate("MainWindow", "Сохранение"))
        self.rb_lang_eng.setText(_translate("MainWindow", "ENG"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Дешифровка/шифровка</span></p></body></html>"))
        self.rb_lang_ru.setText(_translate("MainWindow", "RU"))
        self.rb_crypt_decode.setText(_translate("MainWindow", "Дешифровка"))
        self.rb_crypt_code.setText(_translate("MainWindow", "Шифровка"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Язык шифрования</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#0000ff;\">Настройки</span></p></body></html>"))
        self.save_settings_btn.setText(_translate("MainWindow", "Сохранить настройки"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.info.setText(_translate("MainWindow", "Инфо"))
        self.help.setText(_translate("MainWindow", "Помощь"))
        self.history.setText(_translate("MainWindow", "История поиска"))
