# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Start_Window(object):
    def setupUi(self, Start_Window):
        Start_Window.setObjectName("Start_Window")
        Start_Window.resize(481, 237)
        self.centralwidget = QtWidgets.QWidget(Start_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.start_login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_login_btn.setGeometry(QtCore.QRect(190, 120, 101, 31))
        self.start_login_btn.setObjectName("start_login_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 459, 51))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 481, 221))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("background.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.start_login_btn.raise_()
        self.label.raise_()
        Start_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Start_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 481, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        Start_Window.setMenuBar(self.menubar)
        self.info = QtWidgets.QAction(Start_Window)
        self.info.setObjectName("info")
        self.help = QtWidgets.QAction(Start_Window)
        self.help.setObjectName("help")
        self.history = QtWidgets.QAction(Start_Window)
        self.history.setObjectName("history")
        self.menu.addAction(self.info)
        self.menu.addAction(self.help)
        self.menu.addAction(self.history)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Start_Window)
        QtCore.QMetaObject.connectSlotsByName(Start_Window)

    def retranslateUi(self, Start_Window):
        _translate = QtCore.QCoreApplication.translate
        Start_Window.setWindowTitle(_translate("Start_Window", "MainWindow"))
        self.start_login_btn.setText(_translate("Start_Window", "Начать!"))
        self.label.setText(_translate("Start_Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">Вас приветствует программа Amgine!</span></p><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">Подробнее о программе можно посмотреть в меню сверху.</span></p></body></html>"))
        self.menu.setTitle(_translate("Start_Window", "Меню"))
        self.info.setText(_translate("Start_Window", "Инфо"))
        self.help.setText(_translate("Start_Window", "Помощь"))
        self.history.setText(_translate("Start_Window", "История"))
