from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Choice(object):
    def setupUi(self, Ui_MainWindow_Choice):
        Ui_MainWindow_Choice.setWindowTitle('Amgine')
        Ui_MainWindow_Choice.setObjectName("Ui_MainWindow_Choice")
        Ui_MainWindow_Choice.resize(498, 383)
        self.centralwidget = QtWidgets.QWidget(Ui_MainWindow_Choice)
        self.centralwidget.setObjectName("centralwidget")
        self.greet_label = QtWidgets.QLabel(self.centralwidget)
        self.greet_label.setGeometry(QtCore.QRect(20, 0, 421, 51))
        self.greet_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.greet_label.setObjectName("greet_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 351, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(Ui_MainWindow_Choice)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup.addButton(self.radioButton_4)
        self.verticalLayout.addWidget(self.radioButton_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(380, 50, 101, 291))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.start_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.start_button.setObjectName("start_button")
        self.verticalLayout_2.addWidget(self.start_button)
        Ui_MainWindow_Choice.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui_MainWindow_Choice)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 498, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        Ui_MainWindow_Choice.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui_MainWindow_Choice)
        self.statusbar.setObjectName("statusbar")
        Ui_MainWindow_Choice.setStatusBar(self.statusbar)
        self.info = QtWidgets.QAction(Ui_MainWindow_Choice)
        self.info.setObjectName("info")
        self.help = QtWidgets.QAction(Ui_MainWindow_Choice)
        self.help.setObjectName("help")
        self.action_3 = QtWidgets.QAction(Ui_MainWindow_Choice)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.info)
        self.menu.addAction(self.help)
        self.menu.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Ui_MainWindow_Choice)
        QtCore.QMetaObject.connectSlotsByName(Ui_MainWindow_Choice)

    def retranslateUi(self, Ui_MainWindow_Choice):
        Ui_MainWindow_Choice.setWindowTitle('Amgine')
        _translate = QtCore.QCoreApplication.translate
        self.greet_label.setText(_translate("Ui_MainWindow_Choice",
                                            "<html><head/><body><p><span style=\" font-size:16pt; color:#000000;\">Выберите способ шифровки/дешифровки:</span></p></body></html>"))
        self.radioButton.setText(_translate("Ui_MainWindow_Choice", "Шифр Цезаря"))
        self.radioButton_2.setText(_translate("Ui_MainWindow_Choice", "Азбука Морзе"))
        self.radioButton_3.setText(_translate("Ui_MainWindow_Choice", "Шифр Вижинера"))
        self.radioButton_4.setText(_translate("Ui_MainWindow_Choice", "Калькулятор систем исчисления чисел"))
        self.start_button.setText(_translate("Ui_MainWindow_Choice", "Запустить"))
        self.menu.setTitle(_translate("Ui_MainWindow_Choice", "Меню"))
        self.info.setText(_translate("Ui_MainWindow_Choice", "Инфо"))
        self.help.setText(_translate("Ui_MainWindow_Choice", "Помощь"))
        self.action_3.setText(_translate("Ui_MainWindow_Choice", "История поиска"))
