from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mono_Alpha_Add_Dict(object):
    def setupUi(self, Mono_Alpha_Add_Dict):
        Mono_Alpha_Add_Dict.setObjectName("Mono_Alpha_Add_Dict")
        Mono_Alpha_Add_Dict.resize(537, 381)
        Mono_Alpha_Add_Dict.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(Mono_Alpha_Add_Dict)
        self.centralwidget.setObjectName("centralwidget")
        self.le_key = QtWidgets.QLineEdit(self.centralwidget)
        self.le_key.setGeometry(QtCore.QRect(60, 70, 51, 21))
        self.le_key.setObjectName("le_key")
        self.le_value = QtWidgets.QLineEdit(self.centralwidget)
        self.le_value.setGeometry(QtCore.QRect(180, 70, 51, 21))
        self.le_value.setObjectName("le_value")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 70, 31, 21))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 70, 51, 21))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(250, 70, 75, 23))
        self.btn_add.setObjectName("btn_add")
        self.btn_check = QtWidgets.QPushButton(self.centralwidget)
        self.btn_check.setGeometry(QtCore.QRect(20, 140, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored,
                                           QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_check.sizePolicy().hasHeightForWidth())
        self.btn_check.setSizePolicy(sizePolicy)
        self.btn_check.setObjectName("btn_check")
        self.textBrowser_check = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_check.setGeometry(QtCore.QRect(120, 111, 411, 191))
        self.textBrowser_check.setObjectName("textBrowser_check")
        self.btn_save_dict = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_dict.setGeometry(QtCore.QRect(450, 310, 81, 41))
        self.btn_save_dict.setObjectName("btn_save_dict")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 241, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rb_cap_on = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum,
                                           QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_cap_on.sizePolicy().hasHeightForWidth())
        self.rb_cap_on.setSizePolicy(sizePolicy)
        self.rb_cap_on.setText("")
        self.rb_cap_on.setChecked(True)
        self.rb_cap_on.setObjectName("rb_cap_on")
        self.buttonGroup = QtWidgets.QButtonGroup(Mono_Alpha_Add_Dict)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rb_cap_on)
        self.horizontalLayout.addWidget(self.rb_cap_on)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.rb_cap_off = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum,
                                           QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_cap_off.sizePolicy().hasHeightForWidth())
        self.rb_cap_off.setSizePolicy(sizePolicy)
        self.rb_cap_off.setText("")
        self.rb_cap_off.setChecked(False)
        self.rb_cap_off.setObjectName("rb_cap_off")
        self.buttonGroup.addButton(self.rb_cap_off)
        self.horizontalLayout.addWidget(self.rb_cap_off)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(300, 0, 231, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rb_mirrior_on = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_mirrior_on.sizePolicy().hasHeightForWidth())
        self.rb_mirrior_on.setSizePolicy(sizePolicy)
        self.rb_mirrior_on.setText("")
        self.rb_mirrior_on.setChecked(True)
        self.rb_mirrior_on.setObjectName("rb_mirrior_on")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Mono_Alpha_Add_Dict)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.rb_mirrior_on)
        self.horizontalLayout_2.addWidget(self.rb_mirrior_on)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.rb_mirror_off = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum,
                                           QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_mirror_off.sizePolicy().hasHeightForWidth())
        self.rb_mirror_off.setSizePolicy(sizePolicy)
        self.rb_mirror_off.setText("")
        self.rb_mirror_off.setObjectName("rb_mirror_off")
        self.buttonGroup_2.addButton(self.rb_mirror_off)
        self.horizontalLayout_2.addWidget(self.rb_mirror_off)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored,
                                           QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.label_error = QtWidgets.QLabel(self.centralwidget)
        self.label_error.setGeometry(QtCore.QRect(10, 310, 431, 41))
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(-4, -8, 541, 371))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("background.jpg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_10.raise_()
        self.le_key.raise_()
        self.le_value.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.btn_add.raise_()
        self.btn_check.raise_()
        self.textBrowser_check.raise_()
        self.btn_save_dict.raise_()
        self.verticalLayoutWidget.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.label_5.raise_()
        self.label_error.raise_()
        Mono_Alpha_Add_Dict.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Mono_Alpha_Add_Dict)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 537, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        Mono_Alpha_Add_Dict.setMenuBar(self.menubar)
        self.info = QtWidgets.QAction(Mono_Alpha_Add_Dict)
        self.info.setObjectName("info")
        self.history = QtWidgets.QAction(Mono_Alpha_Add_Dict)
        self.history.setObjectName("history")
        self.help = QtWidgets.QAction(Mono_Alpha_Add_Dict)
        self.help.setObjectName("help")
        self.menu.addAction(self.info)
        self.menu.addAction(self.help)
        self.menu.addAction(self.history)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Mono_Alpha_Add_Dict)
        QtCore.QMetaObject.connectSlotsByName(Mono_Alpha_Add_Dict)

    def retranslateUi(self, Mono_Alpha_Add_Dict):
        _translate = QtCore.QCoreApplication.translate
        Mono_Alpha_Add_Dict.setWindowTitle(_translate("Mono_Alpha_Add_Dict", "Amgine Monoalphabet"))
        self.label.setText(_translate("Mono_Alpha_Add_Dict",
                                      "<html><head/><body><p><span style=\" color:#ffffff;\">Ключ</span></p></body></html>"))
        self.label_2.setText(_translate("Mono_Alpha_Add_Dict",
                                        "<html><head/><body><p><span style=\" color:#ffffff;\">Значение</span></p></body></html>"))
        self.btn_add.setText(_translate("Mono_Alpha_Add_Dict", "Добавить"))
        self.btn_check.setText(_translate("Mono_Alpha_Add_Dict", "Проверить"))
        self.textBrowser_check.setHtml(_translate("Mono_Alpha_Add_Dict",
                                                  "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                  "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                  "p, li { white-space: pre-wrap; }\n"
                                                  "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                                  "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p></body></html>"))
        self.btn_save_dict.setText(_translate("Mono_Alpha_Add_Dict", "Сохранить"))
        self.label_3.setText(_translate("Mono_Alpha_Add_Dict",
                                        "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Автоматическое добавление заглавных букв</span></p></body></html>"))
        self.label_6.setText(_translate("Mono_Alpha_Add_Dict",
                                        "<html><head/><body><p><span style=\" color:#ffffff;\">Да</span></p></body></html>"))
        self.label_8.setText(_translate("Mono_Alpha_Add_Dict",
                                        "<html><head/><body><p><span style=\" color:#ffffff;\">Нет</span></p></body></html>"))
        self.label_4.setText(_translate("Mono_Alpha_Add_Dict",
                                        "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">&quot;Зеркальное&quot; добавление</span></p></body></html>"))
        self.label_7.setText(_translate("Mono_Alpha_Add_Dict",
                                        "<html><head/><body><p><span style=\" color:#ffffff;\"> Да</span></p></body></html>"))
        self.label_9.setText(_translate("Mono_Alpha_Add_Dict",
                                        "<html><head/><body><p><span style=\" color:#ffffff;\">Нет</span></p></body></html>"))
        self.label_5.setText(_translate("Mono_Alpha_Add_Dict",
                                        "<html><head/><body><p><span style=\" color:#ffffff;\">Проверить алфавит</span></p></body></html>"))
        self.menu.setTitle(_translate("Mono_Alpha_Add_Dict", "Меню"))
        self.info.setText(_translate("Mono_Alpha_Add_Dict", "Инфо"))
        self.history.setText(_translate("Mono_Alpha_Add_Dict", "История"))
        self.help.setText(_translate("Mono_Alpha_Add_Dict", "Помощь"))
